package br.edu.univas.tcc.fabricaCalcas.model;

// Generated Aug 3, 2015 12:33:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AtividadeOrdem generated by hbm2java
 */
@Entity
@Table(name = "atividade_ordem", catalog = "mydb")
public class AtividadeOrdem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAtividadeOrdem;
	private Atividade atividadePredecessora;
	private Atividade atividadeByIdAtividade;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_atividade_ordem", unique = true, nullable = false)
	public Integer getIdAtividadeOrdem() {
		return this.idAtividadeOrdem;
	}

	public void setIdAtividadeOrdem(Integer idAtividadeOrdem) {
		this.idAtividadeOrdem = idAtividadeOrdem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_predecessora", nullable = false)
	public Atividade getAtividadePredecessora() {
		return this.atividadePredecessora;
	}

	public void setAtividadePredecessora(Atividade atividadePredecessora) {
		this.atividadePredecessora = atividadePredecessora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_atividade", nullable = false)
	public Atividade getAtividadeByIdAtividade() {
		return this.atividadeByIdAtividade;
	}

	public void setAtividadeByIdAtividade(Atividade atividadeByIdAtividade) {
		this.atividadeByIdAtividade = atividadeByIdAtividade;
	}

}
