package br.edu.univas.tcc.fabricaCalcas.model;

// Generated Aug 3, 2015 12:33:54 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Atividade generated by hbm2java
 */
@Entity
@Table(name = "atividade", catalog = "mydb")
public class Atividade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAtividade;
	private Processo processo;
	private Habilidade habilidade;
	private String nomeAtividade;
	private boolean atividadeFinal;
	private Set<AtividadeOrdem> atividadeOrdemsForIdAtividade = new HashSet<AtividadeOrdem>(0);
	private Set<AtividadeOrdem> atividadesPredecessoras = new HashSet<AtividadeOrdem>(0);

	public Atividade() {
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return habilidade.getNomeHabilidade();
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_atividade", unique = true, nullable = false)
	public Integer getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(Integer idAtividade) {
		this.idAtividade = idAtividade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_processo", nullable = false)
	public Processo getProcesso() {
		return this.processo;
	}

	public void setProcesso(Processo processo) {
		this.processo = processo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hablidade", nullable = false)
	public Habilidade getHabilidade() {
		return this.habilidade;
	}

	public void setHabilidade(Habilidade habilidade) {
		this.habilidade = habilidade;
	}
	
	@Column(name="nome_atividade", nullable = false)
	public String getNomeAtividade() {
		return nomeAtividade;
	}

	public void setNomeAtividade(String nomeAtividade) {
		this.nomeAtividade = nomeAtividade;
	}

	@Column(name="is_atividade_final",nullable=false)
	public boolean isAtividadeFinal() {
		return atividadeFinal;
	}

	public void setAtividadeFinal(boolean atividadeFinal) {
		this.atividadeFinal = atividadeFinal;
	}


	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "atividadeByIdAtividade")
	public Set<AtividadeOrdem> getAtividadeOrdemsForIdAtividade() {
		return this.atividadeOrdemsForIdAtividade;
	}

	
	public void setAtividadeOrdemsForIdAtividade(
			Set<AtividadeOrdem> atividadeOrdemsForIdAtividade) {
		this.atividadeOrdemsForIdAtividade = atividadeOrdemsForIdAtividade;
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL ,mappedBy = "atividadePredecessora")
	public Set<AtividadeOrdem> getAtividadesPredecessoras() {
		return this.atividadesPredecessoras;
	}

	public void setAtividadesPredecessoras(Set<AtividadeOrdem> atividadesPredecessoras) {
		this.atividadesPredecessoras = atividadesPredecessoras;
	}
	
}
