package br.edu.univas.tcc.fabricaCalcas.model;

// Generated Aug 3, 2015 12:33:54 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Costureira generated by hbm2java
 */
@Entity
@Table(name = "costureira", catalog = "mydb")
public class Costureira implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCostureira;
	private String nomeCostureira;
	private float disponibilidade;
	private Set<CostureiraHabilidade> costureiraHabilidades = new HashSet<CostureiraHabilidade>(0);
	
	
	private float disponibilidadeProvisoria;


	public Costureira() {
	}

	public Costureira(String nomeCostureira,
			Set<CostureiraHabilidade> costureiraHabilidades) {
		this.nomeCostureira = nomeCostureira;
		this.costureiraHabilidades = costureiraHabilidades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_costureira", unique = true, nullable = false)
	public Integer getIdCostureira() {
		return this.idCostureira;
	}

	public void setIdCostureira(Integer idCostureira) {
		this.idCostureira = idCostureira;
	}

	@Column(name = "nome_costureira", length = 45)
	public String getNomeCostureira() {
		return this.nomeCostureira;
	}

	public void setNomeCostureira(String nomeCostureira) {
		this.nomeCostureira = nomeCostureira;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "costureira")
	public Set<CostureiraHabilidade> getCostureiraHabilidades() {
		return this.costureiraHabilidades;
	}
	
	@Column(name = "disponibilidade")
	public float getDisponibilidade() {
		return disponibilidade;
	}

	public void setDisponibilidade(float disponibilidade) {
		this.disponibilidade = disponibilidade;
	}

	public void setCostureiraHabilidades(
			Set<CostureiraHabilidade> costureiraHabilidades) {
		this.costureiraHabilidades = costureiraHabilidades;
	}
	
	@Transient
	public float getDisponibilidadeProvisoria() {
		return disponibilidadeProvisoria;
	}

	public void setDisponibilidadeProvisoria(float disponibilidadeProvisoria) {
		this.disponibilidadeProvisoria = disponibilidadeProvisoria;
	}

}
