package br.edu.univas.tcc.fabricaCalcas.model;

// Generated Aug 3, 2015 12:33:54 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CostureiraHabilidade generated by hbm2java
 */
@Entity
@Table(name = "costureira_habilidade", catalog = "mydb")
public class CostureiraHabilidade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCostureiraHabilidade;
	private Habilidade habilidade;
	private Costureira costureira;
	private float precoPorPeca;
	private int tempoPorPeca;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_costureira_habilidade", unique = true, nullable = false)
	public Integer getIdCostureiraHabilidade() {
		return this.idCostureiraHabilidade;
	}

	public void setIdCostureiraHabilidade(Integer idCostureiraHabilidade) {
		this.idCostureiraHabilidade = idCostureiraHabilidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_habilidade", nullable = false)
	public Habilidade getHabilidade() {
		return this.habilidade;
	}

	public void setHabilidade(Habilidade habilidade) {
		this.habilidade = habilidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_costureira", nullable = false)
	public Costureira getCostureira() {
		return this.costureira;
	}

	public void setCostureira(Costureira costureira) {
		this.costureira = costureira;
	}
	
	@Column(name="preco_por_peca", nullable = false)
	public float getPrecoPorPeca() {
		return precoPorPeca;
	}

	public void setPrecoPorPeca(float precoPorPeca) {
		this.precoPorPeca = precoPorPeca;
	}

	@Column(name="tempo_por_peca", nullable = false)
	public int getTempoPorPeca() {
		return tempoPorPeca;
	}

	public void setTempoPorPeca(int tempoPorPeca) {
		this.tempoPorPeca = tempoPorPeca;
	}
}
