package br.edu.univas.tcc.fabricaCalcas.model;

// Generated Aug 3, 2015 12:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Habilidade generated by hbm2java
 */
@Entity
@Table(name = "habilidade", catalog = "mydb")
public class Habilidade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHabilidade;
	private String nomeHabilidade;
	private Set<CostureiraHabilidade> costureiraHabilidades = new HashSet<CostureiraHabilidade>(0);
	private Set<Atividade> atividades = new HashSet<Atividade>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_habilidade", unique = true, nullable = false)
	public Integer getIdHabilidade() {
		return this.idHabilidade;
	}

	public void setIdHabilidade(Integer idHabilidade) {
		this.idHabilidade = idHabilidade;
	}

	@Column(name = "nome_habilidade", length = 45)
	public String getNomeHabilidade() {
		return this.nomeHabilidade;
	}

	public void setNomeHabilidade(String nomeHabilidade) {
		this.nomeHabilidade = nomeHabilidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habilidade")
	public Set<CostureiraHabilidade> getCostureiraHabilidades() {
		return this.costureiraHabilidades;
	}

	public void setCostureiraHabilidades(
			Set<CostureiraHabilidade> costureiraHabilidades) {
		this.costureiraHabilidades = costureiraHabilidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habilidade")
	public Set<Atividade> getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Set<Atividade> atividades) {
		this.atividades = atividades;
	}

}
