package br.edu.univas.tcc.fabricaCalcas.model;

// Generated Aug 3, 2015 12:33:54 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processo generated by hbm2java
 */
@Entity
@Table(name = "processo", catalog = "mydb")
public class Processo implements java.io.Serializable, Comparator<Processo> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProcesso;
	private String nomeProcesso;
	private String cliente;
	private Date dataEntrega;
	private Set<Atividade> atividades = new HashSet<Atividade>(0);


	
	public String pegarDataFormatada(){
		if(dataEntrega != null){
			SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
			return sd.format(dataEntrega);
		}
		return null;
	}
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_processo", unique = true, nullable = false)
	public Integer getIdProcesso() {
		return this.idProcesso;
	}

	public void setIdProcesso(Integer idProcesso) {
		this.idProcesso = idProcesso;
	}

	@Column(name = "nome_processo", length = 45)
	public String getNomeProcesso() {
		return this.nomeProcesso;
	}

	public void setNomeProcesso(String nomeProcesso) {
		this.nomeProcesso = nomeProcesso;
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "processo")
	public Set<Atividade> getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Set<Atividade> atividades) {
		this.atividades = atividades;
	}
	
	@Column(name = "cliente", length = 45)
	public String getCliente() {
		return cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="data_entrega")
	public Date getDataEntrega() {
		return dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}


	public int compare(Processo o1, Processo o2) {
		if(o1.getIdProcesso() > o2.getIdProcesso()){
			return -1;
		}else if(o1.getIdProcesso() < o2.getIdProcesso()){
			return 1;
		}else{
			return 0;
		}
	}
	
	

}
